### ISSUE TITLE
Support for textDocument/signatureHelp for parameter hints

### ISSUE THREAD

**Issue by oblitum** [Chilledheart/vim-clangd#13]
This has been implemented recently, a preview can be checked here:

- https://reviews.llvm.org/D38048#889568

More about the topic here:

- http://lists.llvm.org/pipermail/cfe-dev/2017-September/055358.html

**Comment by oblitum** [comment]
Tip: Vim complete-items has an `empty` item that serves for showing menu completions even when the `word` item for insertion text is empty. This is useful for showing current parameter information or current prototypes but not offering any completion text for what is displayed in the popup (popup menu serving just for display).

**Comment by Chilledheart** [comment]
Hi Francisco,

Thanks for working on this, I just saw it was submitted at Oct 2017 and should be at next release at this Month. Really cool!

Regards,
Keyue

**Comment by oblitum** [comment]
That's great. I wasn't following release schedule, thanks for letting me know.
